var diagnosis;
export default diagnosis = [
    {
        tagId: 10,
        leastConcerning: "Bloated belly",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Flatulence and related conditions",
        leastConcerningDescription: "Meteorism",
        mostConcerning: "Hernia",
        mostConcerningDiagnosis: "Abdominal hernia",
        mostConcerningDescription: "Inguinal hernia;Femoral hernia;Umbilical hernia;Ventral hernia;Diaphragmatic hernia;Other abdominal hernia;Unspecified abdominal hernia",
        mostConcerningSpecialist: "Surgery, General practice",
        femaleDiagnosis: ""
        
    },
    {
        tagId: 238,
        leastConcerning: "Excessive feeling of fear",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Phobic anxiety disorders;Other anxiety disorders",
        leastConcerningDescription: "Anxiety disorder",
        mostConcerning: "Depression",
        mostConcerningDiagnosis: "Major depressive disorder",
        mostConcerningDescription: "Bipolar affective disorder;Depressive episode;Recurrent depressive disorder;Persistent mood [affective] disorders",
        mostConcerningSpecialist: "Psychiatry, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 104,
        leastConcerning: "Slipped disc",
        leastConcerningSpecialist: "General practice, Orthopedics, Rheumatology",
        leastConcerningDiagnosis: "Other specified intervertebral disc displacement",
        leastConcerningDescription: "Disc herniation",
        mostConcerning: "Kidney stones",
        mostConcerningDiagnosis: "Calculus of kidney and ureter",
        mostConcerningDescription: "Nephrolith",
        mostConcerningSpecialist: "Urology, General practice",
        femaleDiagnosis: "Dysmenorrhoea, Menstrual cramps",
    },
    {
        tagId: 75,
        leastConcerning: "Hypersensitivity reaction",
        leastConcerningSpecialist: "Allergology",
        leastConcerningDiagnosis: "Allergy, unspecified",
        leastConcerningDescription: "Allergy",
        mostConcerning: "Drug side effect",
        mostConcerningDiagnosis: "Unspecified adverse effect of drug or medicament",
        mostConcerningDescription: "Adverse drug reaction",
        mostConcerningSpecialist: "General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 170,
        leastConcerning: "Hypersensitivity reaction",
        leastConcerningSpecialist: "Allergology",
        leastConcerningDiagnosis: "Allergy, unspecified",
        leastConcerningDescription: "Allergy",
        mostConcerning: "",
        mostConcerningDiagnosis: " ",
        mostConcerningDescription: "",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
    {
        tagId: 17,
        leastConcerning: "Flu",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Influenza due to other identified influenza virus;Influenza, virus not identified",
        leastConcerningDescription: "Influenza",
        mostConcerning: "Reflux disease",
        mostConcerningDiagnosis: "Gastro-oesophageal reflux disease",
        mostConcerningDescription: "Gastroesophageal reflux disease",
        mostConcerningSpecialist: "Gastroenterology",
        femaleDiagnosis: ""
    },
    {
        tagId: 31,
        leastConcerning: "Excessive feeling of fear",
        leastConcerningSpecialist: "Psychiatry",
        leastConcerningDiagnosis: "Excessive feeling of fear",
        leastConcerningDescription: "Phobic anxiety disorders; Other anxiety disorders",
        mostConcerning: "Coronary heart disease",
        mostConcerningDiagnosis: "Angina pectoris;Acute myocardial infarction;Subsequent myocardial infarction;Certain current complications following acute myocardial infarction;Other acute ischaemic heart diseases;Chronic ischaemic heart disease",
        mostConcerningDescription: "Coronary artery disease",
        mostConcerningSpecialist: "Cardiology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 175,
        leastConcerning: "Flu",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Influenza",
        leastConcerningDescription: "Influenza due to other identified influenza virus;Influenza, virus not identified",
        mostConcerning: "Acute inflammation of lung",
        mostConcerningDiagnosis: "Pneumonia",
        mostConcerningDescription: "Viral pneumonia, not elsewhere classified;Pneumonia due to Streptococcus pneumoniae;Pneumonia due to Haemophilus influenzae;Bacterial pneumonia, not elsewhere classified;Pneumonia due to other infectious organisms, not elsewhere classified;Pneumonia in diseases classified elsewhere;Pneumonia, organism unspecified;Congenital pneumonia",
        mostConcerningSpecialist: "Pulmonology, Internal medicine, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 139,
        leastConcerning: "Low blood sugar",
        leastConcerningSpecialist: "Endocrinology, General practice, Internal medicine",
        leastConcerningDiagnosis: "Drug-induced hypoglycaemia without coma;Other hypoglycaemia;Hypoglycaemia, unspecified",
        leastConcerningDescription: "Hypoglycaemia",
        mostConcerning: "Overproduction of thyroid hormones",
        mostConcerningDiagnosis: "Hyperthyroidism",
        mostConcerningDescription: "Thyrotoxicosis [hyperthyroidism]",
        mostConcerningSpecialist: "Endocrinology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 15,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Common cold",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Inflammatory disease of the airways",
        mostConcerningDiagnosis: "Asthma",
        mostConcerningDescription: "Bronchial asthma",
        mostConcerningSpecialist: "Allergology, General practice, Pulmonology",
        femaleDiagnosis: ""
    },
    {
        tagId: 207,
        leastConcerning: "Motion sickness",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Kinetosis",
        leastConcerningDescription: "Motion sickness",
        mostConcerning: "Positional vertigo",
        mostConcerningDiagnosis: "Benign paroxysmal vertigo",
        mostConcerningDescription: "Benign paroxysmal positional vertigo",
        mostConcerningSpecialist: "General practice, Neurology, Otolaryngology",
        femaleDiagnosis: ""
    },
    {
        tagId: 244,
        leastConcerning: "Congenital eyelid levator weakness",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Congenital ptosis",
        leastConcerningDescription: "Congenital ptosis",
        mostConcerning: "Damage to the eye muscle nerves",
        mostConcerningDiagnosis: "Ptosis of eyelid",
        mostConcerningDescription: "Paralytic ptosis",
        mostConcerningSpecialist: "General practice, Ophthalmology",
        femaleDiagnosis: ""
    },
    {
        tagId: 273,
        leastConcerning: "Dry eye",
        leastConcerningSpecialist: "General practice, Ophthalmology",
        leastConcerningDiagnosis: "Keratitis and keratoconjunctivitis in other diseases classified elsewhere",
        leastConcerningDescription: "Keratoconjunctivitis sicca",
        mostConcerning: "",
        mostConcerningDiagnosis: "",
        mostConcerningDescription: "",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
    {
        tagId: 87,
        leastConcerning: "Middle ear infection",
        leastConcerningSpecialist: "General practice, Otolaryngology",
        leastConcerningDiagnosis: "Otitis media",
        leastConcerningDescription: "Nonsuppurative otitis media;Suppurative and unspecified otitis media;Otitis media in diseases classified elsewhere",
        mostConcerning: "Inflammation of the external ear canal",
        mostConcerningDiagnosis: "Otitis externa",
        mostConcerningDescription: "Otitis externa",
        mostConcerningSpecialist: "General practice, Otolaryngology",
        femaleDiagnosis: ""
    },
    {
        tagId: 92,
        leastConcerning: "Reflux disease",
        leastConcerningSpecialist: "Gastroenterology, General practice",
        leastConcerningDiagnosis: "Gastro-oesophageal reflux disease",
        leastConcerningDescription: "Gastrooesophageal reflux disease",
        mostConcerning: "Problems with defecation",
        mostConcerningDiagnosis: "Constipation",
        mostConcerningDescription: "Constipation",
        mostConcerningSpecialist: "Gastroenterology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 287,
        leastConcerning: "Chemical eye burn",
        leastConcerningSpecialist: "General practic, Ophthalmology",
        leastConcerningDiagnosis: "Eye corrosion",
        leastConcerningDescription: "Corrosion of cornea and conjunctival sac",
        mostConcerning: "Foreign object in the eye",
        mostConcerningDiagnosis: "Foreign body in the eye",
        mostConcerningDescription: "Foreign body on external eye;Foreign body entering into or through eye or natural orifice",
        mostConcerningSpecialist: "General practice, Ophthalmology",
        femaleDiagnosis: ""
    },
    {
        tagId: 33,
        leastConcerning: "Eye allergy",
        leastConcerningSpecialist: "Allergology,General practice,  Ophthalmology",
        leastConcerningDiagnosis: "Conjunctivitis",
        leastConcerningDescription: "Allergic conjunctivitis",
        mostConcerning: "Pink eye",
        mostConcerningDiagnosis: "Conjunctivitis",
        mostConcerningDescription: "Conjunctivitis",
        mostConcerningSpecialist: "General practice, Ophthalmology",
        femaleDiagnosis: ""
    },
    {
        tagId: 153,
        leastConcerning: "Excessive feeling of fear",
        leastConcerningSpecialist: "General practice, Psychiatry",
        leastConcerningDiagnosis: "Anxiety disorder",
        leastConcerningDescription: "Phobic anxiety disorders;Other anxiety disorders",
        mostConcerning: "Hyperventilation",
        mostConcerningDiagnosis: "Hyperventilation",
        mostConcerningDescription: "Hyperventilation syndrome",
        mostConcerningSpecialist: "General practice, Internal medicine, Psychiatry",
        femaleDiagnosis: ""
    },
    {
        tagId: 76,
        leastConcerning: "Dry eye",
        leastConcerningSpecialist: "General practice, Ophthalmology",
        leastConcerningDiagnosis: "Keratoconjunctivitis sicca",
        leastConcerningDescription: "Keratitis and keratoconjunctivitis in other diseases classified elsewhere",
        mostConcerning: "Injury of the eye",
        mostConcerningDiagnosis: "Eye injury",
        mostConcerningDescription: "Injury of eye and orbit",
        mostConcerningSpecialist: "General practice",
        femaleDiagnosis: "Ophthalmology"
    },
    {
        tagId: 11,
        leastConcerning: "Flu",
        leastConcerningSpecialist: "Internal medicine, General practice",
        leastConcerningDiagnosis: "Influenza",
        leastConcerningDescription: "Influenza due to other identified influenza virus;Influenza, virus not identified",
        mostConcerning: "Cold",
        mostConcerningDiagnosis: "Common cold",
        mostConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerningSpecialist: "General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 57,
        leastConcerning: "Fainting",
        leastConcerningSpecialist: "General practice, Neurology",
        leastConcerningDiagnosis: "Syncope",
        leastConcerningDescription: "Syncope and collapse",
        mostConcerning: "Low blood sugar",
        mostConcerningDiagnosis: "Hypoglycaemia",
        mostConcerningDescription: "Drug-induced hypoglycaemia without coma;Other hypoglycaemia;Hypoglycaemia, unspecified",
        mostConcerningSpecialist: "Endocrinology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 9,
        leastConcerning: "Headache",
        leastConcerningSpecialist: "Neurology, General practice",
        leastConcerningDiagnosis: "Cephalalgia",
        leastConcerningDescription: "Other headache syndromes;Headache",
        mostConcerning: "Concussion",
        mostConcerningDiagnosis: "Concussion",
        mostConcerningDescription: "Mild traumatic brain injury",
        mostConcerningSpecialist: "Internal medicine, Neurology, Surgery",
        femaleDiagnosis: ""
    },
    {
        tagId: 45,
        leastConcerning: "Reflux disease",
        leastConcerningSpecialist: "Gastroenterology, General practice",
        leastConcerningDiagnosis: "Reflux disease",
        leastConcerningDescription: "Gastro-oesophageal reflux disease",
        mostConcerning: "Inflammation of the stomach",
        mostConcerningDiagnosis: "Gastritis",
        mostConcerningDescription: "Acute haemorrhagic gastritis;Other acute gastritis;Alcoholic gastritis;Chronic superficial gastritis;Chronic atrophic gastritis;Chronic gastritis, unspecified;Other gastritis;Gastritis, unspecified",
        mostConcerningSpecialist: "Gastroenterology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 122,
        leastConcerning: "Hiccup",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Singultus",
        leastConcerningDescription: "Hiccough",
        mostConcerning: "Reflux disease",
        mostConcerningDiagnosis: "Gastro-oesophageal reflux disease",
        mostConcerningDescription: "Gastroesophageal reflux disease",
        mostConcerningSpecialist: "Gastroenterology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 149,
        leastConcerning: "Overproduction of thyroid hormones",
        leastConcerningSpecialist: "Endocrinology, General practice ,Internal medicine",
        leastConcerningDiagnosis: "Hyperthyroidism",
        leastConcerningDescription: "Thyrotoxicosis [hyperthyroidism]",
        mostConcerning: "Poisoning",
        mostConcerningDiagnosis: "Intoxication",
        mostConcerningDescription: "Poisoning by systemic antibiotics;Poisoning by other systemic anti-infectives and antiparasitics;Poisoning by hormones and their synthetic substitutes and antagonists, not elsewhere classified;Poisoning by nonopioid analgesics, antipyretics and antirheumatics;Poisoning by narcotics and psychodysleptics [hallucinogens];Poisoning by anaesthetics and therapeutic gases;Poisoning by antiepileptic, sedative-hypnotic and antiparkinsonism drugs;Poisoning by psychotropic drugs, not elsewhere classified;Poisoning by drugs primarily affecting the autonomic nervous system;Poisoning by primarily systemic and haematological agents, not elsewhere classified;Poisoning by agents primarily affecting the cardiovascular system;Poisoning by agents primarily affecting the gastrointestinal system;Poisoning by agents primarily acting on smooth and skeletal muscles and the respiratory system;Poisoning by topical agents primarily affecting skin and mucous membrane and by ophthalmological, otorhinolaryngological and dental drugs;Poisoning by diuretics and other and unspecified drugs, medicaments and biological substances",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 40,
        leastConcerning: "Imbalance of body minerals",
        leastConcerningSpecialist: "Nephrolog, Internal medicine, General practice",
        leastConcerningDiagnosis: "Electrolyte imbalance",
        leastConcerningDescription: "Other disorders of fluid, electrolyte and acid-base balance",
        mostConcerning: "Diabetes",
        mostConcerningDiagnosis: "Diabetes mellitus",
        mostConcerningDescription: "Type 1 diabetes mellitus;Type 2 diabetes mellitus;Malnutrition-related diabetes mellitus;Other specified diabetes mellitus;Unspecified diabetes mellitus",
        mostConcerningSpecialist: "Endocrinology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 73,
        leastConcerning: "Eye allergy",
        leastConcerningSpecialist: "Allergology, General practice, Ophthalmology",
        leastConcerningDiagnosis: "Conjunctivitis",
        leastConcerningDescription: "Allergic conjunctivitis",
        mostConcerning: "Pink eye",
        mostConcerningDiagnosis: "Conjunctivitis",
        mostConcerningDescription: "Conjunctivitis",
        mostConcerningSpecialist: "General practice, Ophthalmology",
        femaleDiagnosis: ""
    },
    {
        tagId: 96,
        leastConcerning: "Flu-related rhinitis",
        leastConcerningSpecialist: "Otolaryngology, General practice",
        leastConcerningDiagnosis: "Infectious rhinitis",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Hay fever",
        mostConcerningDiagnosis: "Allergic rhinitis",
        mostConcerningDescription: "Vasomotor and allergic rhinitis",
        mostConcerningSpecialist: "Allergology, General practice, Otolaryngology",
        femaleDiagnosis: ""
    },
    {
        tagId: 35,
        leastConcerning: "Food allergy",
        leastConcerningSpecialist: "Otolaryngology, Allergology, Dermatology, General practice, Internal medicine",
        leastConcerningDiagnosis: "Allergic food hypersensitivity",
        leastConcerningDescription: "Allergic food hypersensitivity",
        mostConcerning: "Hypersensitivity reaction",
        mostConcerningDiagnosis: "Allergy",
        mostConcerningDescription: "Allergy, unspecified",
        mostConcerningSpecialist: "General practice, Allergology",
        femaleDiagnosis: ""
    },
    {
        tagId: 235,
        leastConcerning: "Poisoning",
        leastConcerningSpecialist: "Internal medicine, General practice",
        leastConcerningDiagnosis: "Intoxication",
        leastConcerningDescription: "Poisoning by systemic antibiotics;Poisoning by other systemic anti-infectives and antiparasitics;Poisoning by hormones and their synthetic substitutes and antagonists, not elsewhere classified;Poisoning by nonopioid analgesics, antipyretics and antirheumatics;Poisoning by narcotics and psychodysleptics [hallucinogens];Poisoning by anaesthetics and therapeutic gases;Poisoning by antiepileptic, sedative-hypnotic and antiparkinsonism drugs;Poisoning by psychotropic drugs, not elsewhere classified;Poisoning by drugs primarily affecting the autonomic nervous system;Poisoning by primarily systemic and haematological agents, not elsewhere classified;Poisoning by agents primarily affecting the cardiovascular system;Poisoning by agents primarily affecting the gastrointestinal system;Poisoning by agents primarily acting on smooth and skeletal muscles and the respiratory system;Poisoning by topical agents primarily affecting skin and mucous membrane and by ophthalmological, otorhinolaryngological and dental drugs;Poisoning by diuretics and other and unspecified drugs, medicaments and biological substances",
        mostConcerning: "Concussion",
        mostConcerningDiagnosis: "Concussion",
        mostConcerningDescription: "Mild traumatic brain injury",
        mostConcerningSpecialist: "General practice, Internal medicine, Neurology, Surgery",
        femaleDiagnosis: ""
    },
    {
        tagId: 112,
        leastConcerning: "Lack of supply of thyroid hormones",
        leastConcerningSpecialist: "Endocrinology, General practice, Internal medicine",
        leastConcerningDiagnosis: "Hypothyroidism, unspecified",
        leastConcerningDescription: "Lack of supply of thyroid hormones",
        mostConcerning: "Pregnancy",
        mostConcerningDiagnosis: "Gravidity",
        mostConcerningDescription: "Pregnant state, incidental",
        mostConcerningSpecialist: "Gynecology, General practice",
        femaleDiagnosis: "Pregnancy, incidental, "
    },
    {
        tagId: 123,
        leastConcerning: "Pregnancy",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Gravidity, Pregnancy",
        leastConcerningDescription: "Pregnant state, incidental",
        mostConcerning: "Tubal pregnancy",
        mostConcerningDiagnosis: "Ectopic pregnancy",
        mostConcerningDescription: "Ectopic pregnancy",
        mostConcerningSpecialist: "Gynecology, General practice",
        femaleDiagnosis: "Tubal pregnancy/Pregnancy"
    },
    {
        tagId: 44,
        leastConcerning: "Food poisoning",
        leastConcerningSpecialist: "Internal medicine, General practice",
        leastConcerningDiagnosis: "Foodborne illness",
        leastConcerningDescription: "Other bacterial foodborne intoxications, not elsewhere classified;Other salmonella infections;Shigellosis;Other bacterial intestinal infections",
        mostConcerning: "Stomach flu",
        mostConcerningDiagnosis: "Gastroenteritis",
        mostConcerningDescription: "Salmonella enteritis;Viral and other specified intestinal infections;Other gastroenteritis and colitis of infectious and unspecified origin;Influenza with other manifestations, other influenza virus identified;Influenza with other manifestations, virus not identified;Other noninfective gastroenteritis and colitis",
        mostConcerningSpecialist: "Internal medicine, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 136,
        leastConcerning: "Bad sleeping habits",
        leastConcerningSpecialist: "General practice, Neurology",
        leastConcerningDiagnosis: "Poor sleep hygiene",
        leastConcerningDescription: "Disorders of initiating and maintaining sleep [insomnias];Other problems related to lifestyle",
        mostConcerning: "Strain of the neck muscles",
        mostConcerningDiagnosis: "Muscle tightness in neck",
        mostConcerningDescription: "Sprain and strain of joints and ligaments of other and unspecified parts of neck;Dislocations, sprains and strains involving head with neck",
        mostConcerningSpecialist: "General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 114,
        leastConcerning: "Overproduction of thyroid hormones",
        leastConcerningSpecialist: "Internal medicine, General practice, Endocrinology",
        leastConcerningDiagnosis: "Hyperthyroidism",
        leastConcerningDescription: "Thyrotoxicosis [hyperthyroidism]",
        mostConcerning: "State of stress",
        mostConcerningDiagnosis: "Stress",
        mostConcerningDescription: "Other reactions to severe stress;Reaction to severe stress, unspecified",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
    {
        tagId: 133,
        leastConcerning: "Mitral regurgitation",
        leastConcerningSpecialist: "Cardiology, General practice, Internal medicine",
        leastConcerningDiagnosis: "Mitral valve insufficienc",
        leastConcerningDescription: "Rheumatic mitral insufficiency;Mitral (valve) insufficiency;Congenital mitral insufficiency",
        mostConcerning: "Water accumulation in the lungs",
        mostConcerningDiagnosis: "Pulmonary oedema",
        mostConcerningDescription: "Pulmonary edema",
        mostConcerningSpecialist: "General practice, Internal medicine, Pulmonology",
        femaleDiagnosis: ""
    },
    {
        tagId: 12,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Acute nasopharyngitis [common cold]",
        leastConcerningDescription: "Common cold",
        mostConcerning: "Flu",
        mostConcerningDiagnosis: "Influenza",
        mostConcerningDescription: "Influenza due to other identified influenza virus;Influenza, virus not identified",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 203,
        leastConcerning: "Inflammation of the nose and throat",
        leastConcerningSpecialist: "General practice, Otolaryngology",
        leastConcerningDiagnosis: "Nasopharyngitis",
        leastConcerningDescription: "Acute pharyngitis;Chronic pharyngitis",
        mostConcerning: "Inflammation of the tonsils",
        mostConcerningDiagnosis: "Tonsillitis",
        mostConcerningDescription: "Acute tonsillitis;Chronic tonsillitis",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 37,
        leastConcerning: "Heart racing",
        leastConcerningSpecialist: "Cardiology, General practice",
        leastConcerningDiagnosis: "Palpitations",
        leastConcerningDescription: "Palpitations",
        mostConcerning: "Irregular heart rhythm in atria",
        mostConcerningDiagnosis: "Atrial fibrillation",
        mostConcerningDescription: "Atrial fibrillation and flutter",
        mostConcerningSpecialist: "Cardiology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 140,
        leastConcerning: "Disseminated sclerosis",
        leastConcerningSpecialist: "Neurology, General practice",
        leastConcerningDiagnosis: "Multiple sclerosis",
        leastConcerningDescription: "Multiple sclerosis",
        mostConcerning: "Stroke",
        mostConcerningDiagnosis: "Cerebrovascular accident",
        mostConcerningDescription: "Intracerebral haemorrhage;Other nontraumatic intracranial haemorrhage;Cerebral infarction;Stroke, not specified as haemorrhage or infarction",
        mostConcerningSpecialist: "General practice, Internal medicineNeurology",
        femaleDiagnosis: ""
    },
    {
        tagId: 54,
        leastConcerning: "State of stress",
        leastConcerningSpecialist: "Psychiatry, General practice",
        leastConcerningDiagnosis: "Stress",
        leastConcerningDescription: "Other reactions to severe stress;Reaction to severe stress, unspecified",
        mostConcerning: "Spastic colon",
        mostConcerningDiagnosis: "Irritable bowel syndrome",
        mostConcerningDescription: "Irritable bowel syndrome",
        mostConcerningSpecialist: "Gastroenterology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 14,
        leastConcerning: "Flu-related rhinitis",
        leastConcerningSpecialist: "Otolaryngology, General practice",
        leastConcerningDiagnosis: "Infectious rhinitis",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Inflammation of paranasal sinuses",
        mostConcerningDiagnosis: "Sinusitis",
        mostConcerningDescription: "Acute sinusitis;Chronic sinusitis",
        mostConcerningSpecialist: "Otolaryngology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 29,
        leastConcerning: "Inflammatory disease of the airways",
        leastConcerningSpecialist: "Allergology, General practice, Pulmonology",
        leastConcerningDiagnosis: "Asthma",
        leastConcerningDescription: "Bronchial asthma",
        mostConcerning: "Acute inflammation of lung",
        mostConcerningDiagnosis: "Pneumonia",
        mostConcerningDescription: "Viral pneumonia, not elsewhere classified;Pneumonia due to Streptococcus pneumoniae;Pneumonia due to Haemophilus influenzae;Bacterial pneumonia, not elsewhere classified;Pneumonia due to other infectious organisms, not elsewhere classified;Pneumonia in diseases classified elsewhere;Pneumonia, organism unspecified;Congenital pneumonia",
        mostConcerningSpecialist: "Pulmonology, Internal medicine, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 124,
        leastConcerning: "Contact eczema",
        leastConcerningSpecialist: "Internal medicine, General practice, Dermatology, Allergology",
        leastConcerningDiagnosis: "Contact dermatitis",
        leastConcerningDescription: "Allergic contact dermatitis;Irritant contact dermatitis;Unspecified contact dermatitis",
        mostConcerning: "Dermatitis",
        mostConcerningDiagnosis: "Eczema",
        mostConcerningDescription: "Atopic dermatitis;Seborrhoeic dermatitis;Allergic contact dermatitis;Irritant contact dermatitis;Unspecified contact dermatitis;Lichen simplex chronicus and prurigo;Other dermatitis",
        mostConcerningSpecialist: "General practice, Dermatology",
        femaleDiagnosis: ""
    },

    {
        tagId: 52,
        leastConcerning: "Sleeping disorder",
        leastConcerningSpecialist: "Neurology, General practice",
        leastConcerningDiagnosis: "Somnipathy",
        leastConcerningDescription: "Sleep disorders;Nonorganic sleep disorders",
        mostConcerning: "State of stress",
        mostConcerningDiagnosis: "Stress",
        mostConcerningDescription: "Other reactions to severe stress;Reaction to severe stress, unspecified",
        mostConcerningSpecialist: "Psychiatry, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 95,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Common cold",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Flu-related rhinitis",
        mostConcerningDiagnosis: "Infectious rhinitis",
        mostConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerningSpecialist: "Otolaryngology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 13,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Common cold",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Inflammation of the nose and throa",
        mostConcerningDiagnosis: "Nasopharyngitis",
        mostConcerningDescription: "Acute pharyngitis;Chronic pharyngitis",
        mostConcerningSpecialist: "Otolaryngology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 13,
        leastConcerning: "Inflammation of the bronchi",
        leastConcerningSpecialist: "General practice, Internal medicine, Pulmonology",
        leastConcerningDiagnosis: "Acute bronchitis",
        leastConcerningDescription: "Acute bronchitis;Acute bronchiolitis with bronchospasm",
        mostConcerning: "Chronic obstructive lung disease",
        mostConcerningDiagnosis: "Chronic obstructive pulmonary disease",
        mostConcerningDescription: "Bronchitis, not specified as acute or chronic;Simple and mucopurulent chronic bronchitis;Unspecified chronic bronchitis;Emphysema;Other chronic obstructive pulmonary disease",
        mostConcerningSpecialist: "General practice, Internal medicine, Pulmonology",
        femaleDiagnosis: ""
    },
    {
        tagId: 64,
        leastConcerning: "Inflammation of the bronchi",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Acute bronchitis",
        leastConcerningDescription: "Inflammation of the bronchi, Acute bronchitis;Acute bronchiolitis with bronchospasm",
        mostConcerning: "Chronic obstructive lung disease",
        mostConcerningDiagnosis: "Bronchitis, not specified as acute or chronic;Simple and mucopurulent chronic bronchitis;Unspecified chronic bronchitis;Emphysema;Other chronic obstructive pulmonary disease",
        mostConcerningDescription: "Chronic obstructive pulmonary diseas",
        mostConcerningSpecialist: "General practice, Internal medicine, Pulmonology",
        femaleDiagnosis: ""
    },
    {
        tagId: 179,
        leastConcerning: "Reflux disease",
        leastConcerningSpecialist: "Gastroenterology",
        leastConcerningDiagnosis: "Reflux disease",
        leastConcerningDescription: "Gastro-oesophageal reflux disease",
        mostConcerning: "Stomach ulcer",
        mostConcerningDiagnosis: "Gastric ulcer;Duodenal ulcer;Peptic ulcer, site unspecified",
        mostConcerningDescription: "Stomach ulcer, Peptic ulcer disease",
        mostConcerningSpecialist: "Gastroenterology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 28,
        leastConcerning: "Flu",
        leastConcerningSpecialist: "General practice, Internal medicine",
        leastConcerningDiagnosis: "",
        leastConcerningDescription: "Influenza due to other identified influenza virus;Influenza, virus not identified",
        mostConcerning: "Sinusitis",
        mostConcerningDiagnosis: "Acute sinusitis;Chronic sinusitis",
        mostConcerningDescription: "Inflammation of paranasal sinuses",
        mostConcerningSpecialist: "Otolaryngology, General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 138,
        leastConcerning: "Excessive overweight",
        leastConcerningSpecialist: "Endocrinology, General practice",
        leastConcerningDiagnosis: "Obesity",
        leastConcerningDescription: "Excessive overweight",
        mostConcerning: "",
        mostConcerningDiagnosis: "",
        mostConcerningDescription: "",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
    {
        tagId: 248,
        leastConcerning: "Bacterial skin infection",
        leastConcerningSpecialist: "Dermatology, General practice",
        leastConcerningDiagnosis: "Bacterial skin infection",
        leastConcerningDescription: "Impetigo;Erysipelas;Cellulitis;Follicular disorder, unspecified;Hidradenitis suppurativa;Eccrine sweat disorders;Cutaneous abscess, furuncle and carbuncle;Staphylococcal scalded skin syndrome;Toxic epidermal necrolysis [Lyell];Necrotizing fasciitis",
        mostConcerning: "Enlarged lymph nodes",
        mostConcerningDiagnosis: "Lymphadenopathy",
        mostConcerningDescription: "Nonspecific lymphadenitis;Acute lymphadenitis;Generalized enlarged lymph nodes",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 169,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Common cold",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "Inflammation of the tonsils",
        mostConcerningDiagnosis: "Tonsillitis",
        mostConcerningDescription: "Acute tonsillitis;Chronic tonsillitis",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 211,
        leastConcerning: "Hypersensitivity reaction",
        leastConcerningSpecialist: "Allergology, General practice",
        leastConcerningDiagnosis: "Allergy",
        leastConcerningDescription: "Allergy, unspecified",
        mostConcerning: "Inflammation of the cornea",
        mostConcerningDiagnosis: "Keratitis",
        mostConcerningDescription: "Keratitis",
        mostConcerningSpecialist: "General practice, Ophthalmology",
        femaleDiagnosis: ""
    },
    {
        tagId: 16,
        leastConcerning: "Sleeping disorder",
        leastConcerningSpecialist: "General practice, Neurology",
        leastConcerningDiagnosis: "Somnipathy",
        leastConcerningDescription: "Sleep disorders;Nonorganic sleep disorders",
        mostConcerning: "Sleep apnea",
        mostConcerningDiagnosis: "Sleep apnea syndrome",
        mostConcerningDescription: "Sleep apnoea;Primary sleep apnoea of newborn",
        mostConcerningSpecialist: "General practice, Neurology, Otolaryngology",
        femaleDiagnosis: ""
    },
    {
        tagId: 115,
        leastConcerning: "Familial tremor",
        leastConcerningSpecialist: "General practice, Neurology",
        leastConcerningDiagnosis: "Essential tremor",
        leastConcerningDescription: "Essential tremor",
        mostConcerning: "Epileptic seizures",
        mostConcerningDiagnosis: "Epilepsy",
        mostConcerningDescription: "Epilepsy;Status epilepticus",
        mostConcerningSpecialist: "General practice, Neurology",
        femaleDiagnosis: ""
    },
    {
        tagId: 144,
        leastConcerning: "Low blood pressure",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Hypotension",
        leastConcerningDescription: "Hypotension",
        mostConcerning: "Fainting after standing up",
        mostConcerningDiagnosis: "Orthostatic syncope",
        mostConcerningDescription: "Syncope and collapse;Orthostatic hypotension",
        mostConcerningSpecialist: "General practice",
        femaleDiagnosis: ""
    },
    {
        tagId: 101,
        leastConcerning: "Food poisoning",
        leastConcerningSpecialist: "General practice, Internal medicine",
        leastConcerningDiagnosis: "Foodborne illness",
        leastConcerningDescription: "Other bacterial foodborne intoxications, not elsewhere classified;Other salmonella infections;Shigellosis;Other bacterial intestinal infections",
        mostConcerning: "Inflammation of the appendix",
        mostConcerningDiagnosis: "Appendicitis",
        mostConcerningDescription: "Acute appendicitis;Other appendicitis;Unspecified appendicitis",
        mostConcerningSpecialist: "General practice, Internal medicine, Surgery",
        femaleDiagnosis: "Pregnancy-related problems"
    },
    {
        tagId: 181,
        leastConcerning: "Inflammation of the stomach",
        leastConcerningSpecialist: "Gastroenterology, General practice",
        leastConcerningDiagnosis: "Gastritis",
        leastConcerningDescription: "Acute haemorrhagic gastritis;Other acute gastritis;Alcoholic gastritis;Chronic superficial gastritis;Chronic atrophic gastritis;Chronic gastritis, unspecified;Other gastritis;Gastritis, unspecified",
        mostConcerning: "Stomach bleeding",
        mostConcerningDiagnosis: "Gastrointestinal bleeding",
        mostConcerningDescription: "Gastrointestinal haemorrhage, unspecified",
        mostConcerningSpecialist: "Gastroenterology, General practice, Internal medicine",
        femaleDiagnosis: ""
    },
    {
        tagId: 56,
        leastConcerning: "Cold",
        leastConcerningSpecialist: "General practice",
        leastConcerningDiagnosis: "Common cold",
        leastConcerningDescription: "Acute nasopharyngitis [common cold]",
        mostConcerning: "",
        mostConcerningDiagnosis: "",
        mostConcerningDescription: "",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
    {
        tagId: 23,
        leastConcerning: "Depression",
        leastConcerningSpecialist: "General practice, Psychiatry",
        leastConcerningDiagnosis: "Major depressive disorder",
        leastConcerningDescription: "Bipolar affective disorder;Depressive episode;Recurrent depressive disorder;Persistent mood [affective] disorders",
        mostConcerning: "Drug side effect",
        mostConcerningDiagnosis: "Adverse drug reaction",
        mostConcerningDescription: "Unspecified adverse effect of drug or medicament",
        mostConcerningSpecialist: "General practice, Internal medicine",
        femaleDiagnosis: "Pregnancy"
    },
    {
        tagId: 30,
        leastConcerning: "Hypersensitivity reaction",
        leastConcerningSpecialist: "Allergology, General practice",
        leastConcerningDiagnosis: "Allergy, unspecified",
        leastConcerningDescription: "Allergy",
        mostConcerning: "",
        mostConcerningDiagnosis: "",
        mostConcerningDescription: "",
        mostConcerningSpecialist: "",
        femaleDiagnosis: ""
    },
]